/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Object that contains links to additional information on specific topics
 */
export interface BankingProductAdditionalInformationV1 { 
    /**
     * General overview of the product
     */
    overviewUri?: string;
    /**
     * Terms and conditions for the product
     */
    termsUri?: string;
    /**
     * Eligibility rules and criteria for the product
     */
    eligibilityUri?: string;
    /**
     * Description of fees, pricing, discounts, exemptions and bonuses for the product
     */
    feesAndPricingUri?: string;
    /**
     * Description of a bundle that this product can be part of
     */
    bundleUri?: string;
}