/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Banking Product Categories
 */
export type BankingProductCategory = 'TRANS_AND_SAVINGS_ACCOUNTS' | 'TERM_DEPOSITS' | 'TRAVEL_CARDS' | 'REGULATED_TRUST_ACCOUNTS' | 'RESIDENTIAL_MORTGAGES' | 'CRED_AND_CHRG_CARDS' | 'PERS_LOANS' | 'MARGIN_LOANS' | 'LEASES' | 'TRADE_FINANCE' | 'OVERDRAFTS' | 'BUSINESS_LOANS';

export const BankingProductCategory = {
    TRANSANDSAVINGSACCOUNTS: 'TRANS_AND_SAVINGS_ACCOUNTS' as BankingProductCategory,
    TERMDEPOSITS: 'TERM_DEPOSITS' as BankingProductCategory,
    TRAVELCARDS: 'TRAVEL_CARDS' as BankingProductCategory,
    REGULATEDTRUSTACCOUNTS: 'REGULATED_TRUST_ACCOUNTS' as BankingProductCategory,
    RESIDENTIALMORTGAGES: 'RESIDENTIAL_MORTGAGES' as BankingProductCategory,
    CREDANDCHRGCARDS: 'CRED_AND_CHRG_CARDS' as BankingProductCategory,
    PERSLOANS: 'PERS_LOANS' as BankingProductCategory,
    MARGINLOANS: 'MARGIN_LOANS' as BankingProductCategory,
    LEASES: 'LEASES' as BankingProductCategory,
    TRADEFINANCE: 'TRADE_FINANCE' as BankingProductCategory,
    OVERDRAFTS: 'OVERDRAFTS' as BankingProductCategory,
    BUSINESSLOANS: 'BUSINESS_LOANS' as BankingProductCategory
};