/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BankingInternationalPayeeBankDetailsBankAddressV1 } from './bankingInternationalPayeeBankDetailsBankAddressV1';

/**
 * International Payee Bank Details
 */
export interface BankingInternationalPayeeBankDetailsV1 { 
    /**
     * Country of the recipient institution. A valid [ISO 3166 Alpha-3](https://www.iso.org/iso-3166-country-codes.html) country code
     */
    country: string;
    /**
     * Account Targeted for payment
     */
    accountNumber: string;
    bankAddress?: BankingInternationalPayeeBankDetailsBankAddressV1;
    /**
     * Swift BIC Type
     */
    beneficiaryBankBIC?: string;
    /**
     * Number for Fedwire payment (Federal Reserve Wire Network)
     */
    fedWireNumber?: string;
    /**
     * Sort code used for account identification in some jurisdictions
     */
    sortCode?: string;
    /**
     * Number for the Clearing House Interbank Payments System
     */
    chipNumber?: string;
    /**
     * International bank routing number
     */
    routingNumber?: string;
    /**
     * The legal entity identifier (LEI) for the beneficiary.  Aligns with [ISO 17442](https://www.iso.org/standard/59771.html)
     */
    legalEntityIdentifier?: string;
}