/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BankingBillerPayeeV1 } from './bankingBillerPayeeV1';
import { BankingDomesticPayeeV1 } from './bankingDomesticPayeeV1';
import { BankingInternationalPayeeV1 } from './bankingInternationalPayeeV1';
import { PayloadTypeBankingScheduledPaymentTo } from './payloadTypeBankingScheduledPaymentTo';

/**
 * Object containing details of the destination of the payment. Used to specify a variety of payment destination types
 */
export interface BankingScheduledPaymentToV1 { 
    toUType: PayloadTypeBankingScheduledPaymentTo;
    /**
     * Present if toUType is set to accountId. Indicates that the payment is to another account that is accessible under the current consent
     */
    accountId?: string;
    /**
     * Present if toUType is set to payeeId. Indicates that the payment is to registered payee that can be accessed using the payee end point. If the Bank Payees scope has not been consented to then a payeeId should not be provided and the full payee details should be provided instead
     */
    payeeId?: string;
    domestic?: BankingDomesticPayeeV1;
    biller?: BankingBillerPayeeV1;
    international?: BankingInternationalPayeeV1;
}