/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Banking Product: Lending Rate Type
 */
export type BankingProductLendingRateType = 'FIXED' | 'VARIABLE' | 'INTRODUCTORY' | 'FLOATING' | 'MARKET_LINKED' | 'DISCOUNT' | 'PENALTY' | 'CASH_ADVANCE' | 'PURCHASE' | 'BUNDLE_DISCOUNT_FIXED' | 'BUNDLE_DISCOUNT_VARIABLE';

export const BankingProductLendingRateType = {
    FIXED: 'FIXED' as BankingProductLendingRateType,
    VARIABLE: 'VARIABLE' as BankingProductLendingRateType,
    INTRODUCTORY: 'INTRODUCTORY' as BankingProductLendingRateType,
    FLOATING: 'FLOATING' as BankingProductLendingRateType,
    MARKETLINKED: 'MARKET_LINKED' as BankingProductLendingRateType,
    DISCOUNT: 'DISCOUNT' as BankingProductLendingRateType,
    PENALTY: 'PENALTY' as BankingProductLendingRateType,
    CASHADVANCE: 'CASH_ADVANCE' as BankingProductLendingRateType,
    PURCHASE: 'PURCHASE' as BankingProductLendingRateType,
    BUNDLEDISCOUNTFIXED: 'BUNDLE_DISCOUNT_FIXED' as BankingProductLendingRateType,
    BUNDLEDISCOUNTVARIABLE: 'BUNDLE_DISCOUNT_VARIABLE' as BankingProductLendingRateType
};