/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Banking Product Feature Type
 */
export type BankingProductFeatureType = 'CARD_ACCESS' | 'ADDITIONAL_CARDS' | 'UNLIMITED_TXNS' | 'FREE_TXNS' | 'FREE_TXNS_ALLOWANCE' | 'LOYALTY_PROGRAM' | 'OFFSET' | 'OVERDRAFT' | 'REDRAW' | 'INSURANCE' | 'BALANCE_TRANSFERS' | 'INTEREST_FREE' | 'INTEREST_FREE_TRANSFERS' | 'DIGITAL_WALLET' | 'DIGITAL_BANKING' | 'NPP_PAYID' | 'NPP_ENABLED' | 'DONATE_INTEREST' | 'BILL_PAYMENT' | 'COMPLEMENTARY_PRODUCT_DISCOUNTS' | 'BONUS_REWARDS' | 'NOTIFICATIONS' | 'OTHER';

export const BankingProductFeatureType = {
    CARDACCESS: 'CARD_ACCESS' as BankingProductFeatureType,
    ADDITIONALCARDS: 'ADDITIONAL_CARDS' as BankingProductFeatureType,
    UNLIMITEDTXNS: 'UNLIMITED_TXNS' as BankingProductFeatureType,
    FREETXNS: 'FREE_TXNS' as BankingProductFeatureType,
    FREETXNSALLOWANCE: 'FREE_TXNS_ALLOWANCE' as BankingProductFeatureType,
    LOYALTYPROGRAM: 'LOYALTY_PROGRAM' as BankingProductFeatureType,
    OFFSET: 'OFFSET' as BankingProductFeatureType,
    OVERDRAFT: 'OVERDRAFT' as BankingProductFeatureType,
    REDRAW: 'REDRAW' as BankingProductFeatureType,
    INSURANCE: 'INSURANCE' as BankingProductFeatureType,
    BALANCETRANSFERS: 'BALANCE_TRANSFERS' as BankingProductFeatureType,
    INTERESTFREE: 'INTEREST_FREE' as BankingProductFeatureType,
    INTERESTFREETRANSFERS: 'INTEREST_FREE_TRANSFERS' as BankingProductFeatureType,
    DIGITALWALLET: 'DIGITAL_WALLET' as BankingProductFeatureType,
    DIGITALBANKING: 'DIGITAL_BANKING' as BankingProductFeatureType,
    NPPPAYID: 'NPP_PAYID' as BankingProductFeatureType,
    NPPENABLED: 'NPP_ENABLED' as BankingProductFeatureType,
    DONATEINTEREST: 'DONATE_INTEREST' as BankingProductFeatureType,
    BILLPAYMENT: 'BILL_PAYMENT' as BankingProductFeatureType,
    COMPLEMENTARYPRODUCTDISCOUNTS: 'COMPLEMENTARY_PRODUCT_DISCOUNTS' as BankingProductFeatureType,
    BONUSREWARDS: 'BONUS_REWARDS' as BankingProductFeatureType,
    NOTIFICATIONS: 'NOTIFICATIONS' as BankingProductFeatureType,
    OTHER: 'OTHER' as BankingProductFeatureType
};