/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Banking: Transaction Type
 */
export type BankingTransactionType = 'FEE' | 'INTEREST_CHARGED' | 'INTEREST_PAID' | 'TRANSFER_OUTGOING' | 'TRANSFER_INCOMING' | 'PAYMENT' | 'DIRECT_DEBIT' | 'OTHER';

export const BankingTransactionType = {
    FEE: 'FEE' as BankingTransactionType,
    INTERESTCHARGED: 'INTEREST_CHARGED' as BankingTransactionType,
    INTERESTPAID: 'INTEREST_PAID' as BankingTransactionType,
    TRANSFEROUTGOING: 'TRANSFER_OUTGOING' as BankingTransactionType,
    TRANSFERINCOMING: 'TRANSFER_INCOMING' as BankingTransactionType,
    PAYMENT: 'PAYMENT' as BankingTransactionType,
    DIRECTDEBIT: 'DIRECT_DEBIT' as BankingTransactionType,
    OTHER: 'OTHER' as BankingTransactionType
};