/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Banking Product Fee Type
 */
export type BankingProductFeeType = 'PERIODIC' | 'TRANSACTION' | 'WITHDRAWAL' | 'DEPOSIT' | 'PAYMENT' | 'PURCHASE' | 'EVENT' | 'UPFRONT' | 'EXIT';

export const BankingProductFeeType = {
    PERIODIC: 'PERIODIC' as BankingProductFeeType,
    TRANSACTION: 'TRANSACTION' as BankingProductFeeType,
    WITHDRAWAL: 'WITHDRAWAL' as BankingProductFeeType,
    DEPOSIT: 'DEPOSIT' as BankingProductFeeType,
    PAYMENT: 'PAYMENT' as BankingProductFeeType,
    PURCHASE: 'PURCHASE' as BankingProductFeeType,
    EVENT: 'EVENT' as BankingProductFeeType,
    UPFRONT: 'UPFRONT' as BankingProductFeeType,
    EXIT: 'EXIT' as BankingProductFeeType
};