/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BankingBillerPayeeV1 } from './bankingBillerPayeeV1';
import { BankingDomesticPayeeV1 } from './bankingDomesticPayeeV1';
import { BankingInternationalPayeeV1 } from './bankingInternationalPayeeV1';
import { BankingPayeeType } from './bankingPayeeType';
import { PayloadTypeBankingPayee } from './payloadTypeBankingPayee';

/**
 * Banking Payee Detailed Information
 */
export interface BankingPayeeDetailV1 { 
    /**
     * ID of the payee adhering to the rules of ID permanence
     */
    payeeId: string;
    /**
     * The short display name of the payee as provided by the customer
     */
    nickname: string;
    /**
     * A description of the payee provided by the customer
     */
    description?: string;
    type: BankingPayeeType;
    /**
     * The date the payee was created by the customer
     */
    creationDate?: string;
    payeeUType: PayloadTypeBankingPayee;
    domestic?: BankingDomesticPayeeV1;
    biller?: BankingBillerPayeeV1;
    international?: BankingInternationalPayeeV1;
}