/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BankingScheduledPaymentRecurrenceEventBasedV1 } from './bankingScheduledPaymentRecurrenceEventBasedV1';
import { BankingScheduledPaymentRecurrenceIntervalScheduleV1 } from './bankingScheduledPaymentRecurrenceIntervalScheduleV1';
import { BankingScheduledPaymentRecurrenceLastWeekdayV1 } from './bankingScheduledPaymentRecurrenceLastWeekdayV1';
import { BankingScheduledPaymentRecurrenceOnceOffV1 } from './bankingScheduledPaymentRecurrenceOnceOffV1';
import { PayloadTypeBankingScheduledPaymentRecurrence } from './payloadTypeBankingScheduledPaymentRecurrence';

/**
 * Describes the detail of the scheduled payment
 */
export interface BankingScheduledPaymentRecurrenceV1 { 
    /**
     * The date of the next payment under the recurrence schedule
     */
    nextPaymentDate?: string;
    recurrenceUType: PayloadTypeBankingScheduledPaymentRecurrence;
    onceOff?: BankingScheduledPaymentRecurrenceOnceOffV1;
    intervalSchedule?: BankingScheduledPaymentRecurrenceIntervalScheduleV1;
    lastWeekDay?: BankingScheduledPaymentRecurrenceLastWeekdayV1;
    eventBased?: BankingScheduledPaymentRecurrenceEventBasedV1;
}