/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BankingProductDiscountV1 } from './bankingProductDiscountV1';
import { BankingProductFeeType } from './bankingProductFeeType';

/**
 * Banking Product Fee Definition
 */
export interface BankingProductFeeV1 { 
    /**
     * Name of the fee
     */
    name: string;
    feeType: BankingProductFeeType;
    /**
     * The amount charged for the fee. One of amount, balanceRate, transactionRate and accruedRate is mandatory
     */
    amount?: string;
    /**
     * A fee rate calculated based on a proportion of the balance. One of amount, balanceRate, transactionRate and accruedRate is mandatory
     */
    balanceRate?: string;
    /**
     * A fee rate calculated based on a proportion of a transaction. One of amount, balanceRate, transactionRate and accruedRate is mandatory
     */
    transactionRate?: string;
    /**
     * A fee rate calculated based on a proportion of the calculated interest accrued on the account. One of amount, balanceRate, transactionRate and accruedRate is mandatory
     */
    accruedRate?: string;
    /**
     * The indicative frequency with which the fee is calculated on the account. Only applies if balanceRate or accruedRate is also present. Formatted according to [ISO 8601 Durations](https://en.wikipedia.org/wiki/ISO_8601#Durations)
     */
    accrualFrequency?: string;
    /**
     * The currency the fee will be charged in
     */
    currency?: string;
    /**
     * Generic field containing additional information relevant to the [feeType](#tocSproductfeetypedoc) specified. Whether mandatory or not is dependent on the value of [feeType](#tocSproductfeetypedoc)
     */
    additionalValue?: string;
    /**
     * Display text providing more information on the fee
     */
    additionalInfo?: string;
    /**
     * Link to a web page with more information on this fee
     */
    additionalInfoUri?: string;
    /**
     * An optional list of discounts to this fee that may be available
     */
    discounts?: Array<BankingProductDiscountV1>;
}