/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DioBankBranch } from './dioBankBranch';
import { DioSchemeType } from './dioSchemeType';

/**
 * A Deep Thought Bank Account Container
 */
export interface DioBankAuthorisedEntity { 
    /**
     * Deep Thought Bank Account Identifier
     */
    id: string;
    schemeType: DioSchemeType;
    /**
     * Description of the authorised entity derived from previously executed direct debits
     */
    description?: string;
    branch?: DioBankBranch;
    /**
     * Australian Business Number for the authorised entity
     */
    abn?: string;
    /**
     * Australian Company Number for the authorised entity
     */
    acn?: string;
    /**
     * Australian Registered Body Number for the authorised entity
     */
    arbn?: string;
}