/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BankingTransactionService } from './bankingTransactionService';
import { DioSchemeType } from './dioSchemeType';
import { PayloadTypeTransactionExtension } from './payloadTypeTransactionExtension';

/**
 * Banking Information
 */
export interface DioBankAccountTransactionNPP { 
    /**
     * Deep Thought Person Identifier
     */
    id: string;
    schemeType: DioSchemeType;
    /**
     * Label of the originating payer. Mandatory for inbound payment
     */
    payer?: string;
    /**
     * Label of the target PayID.  Mandatory for an outbound payment. The name assigned to the BSB/Account Number or PayID (by the owner of the PayID)
     */
    payee?: string;
    extensionUType?: PayloadTypeTransactionExtension;
    /**
     * An extended string description. Only present if specified by the extensionUType field
     */
    extendedDescription: string;
    /**
     * An end to end ID for the payment created at initiation
     */
    endToEndId?: string;
    /**
     * Purpose of the payment.  Format is defined by NPP standards for the x2p1.01 overlay service
     */
    purposeCode?: string;
    service: BankingTransactionService;
}