/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DioLoanRepaymentType } from './dioLoanRepaymentType';
import { DioSchemeType } from './dioSchemeType';

/**
 * Banking Loan Account Details
 */
export interface DioBankAccountLoanAccount { 
    /**
     * Deep Thought Bank Account Loan Identifier
     */
    id: string;
    schemeType: DioSchemeType;
    /**
     * Original Loan Start Date
     */
    creationDateTime?: Date;
    /**
     * Original Loan Value
     */
    creationAmount?: number;
    /**
     * Original Loan Value Currency
     */
    currency?: string;
    /**
     * Original length at creation
     */
    creationLength: string;
    /**
     * Repayment Frequency
     */
    repaymentFrequency: string;
    /**
     * Last Repayment
     */
    lastRepayment: Date;
    /**
     * Next Repayment Amount
     */
    nextRepaymentAmount: number;
    /**
     * Redraw Value Available
     */
    redrawAvailable: number;
    repaymentType: DioLoanRepaymentType;
}