/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DioSchemeType } from './dioSchemeType';

/**
 * Card Transaction Information
 */
export interface DioBankAccountTransactionCard { 
    /**
     * Deep Thought Person Identifier
     */
    id: string;
    schemeType: DioSchemeType;
    /**
     * Name of the merchant for an outgoing payment to a merchant
     */
    merchantName?: string;
    /**
     * Merchant Category Codes
     */
    merchantCategoryCode?: string;
}