/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BankingTransactionStatus } from './bankingTransactionStatus';
import { BankingTransactionType } from './bankingTransactionType';
import { DioBankAccountTransactionAPCS } from './dioBankAccountTransactionAPCS';
import { DioBankAccountTransactionBPAY } from './dioBankAccountTransactionBPAY';
import { DioBankAccountTransactionCard } from './dioBankAccountTransactionCard';
import { DioBankAccountTransactionNPP } from './dioBankAccountTransactionNPP';
import { DioSchemeType } from './dioSchemeType';

/**
 * Banking Information
 */
export interface DioBankAccountTransaction { 
    /**
     * Deep Thought Person Identifier
     */
    id: string;
    schemeType: DioSchemeType;
    type: BankingTransactionType;
    status: BankingTransactionStatus;
    /**
     * The transaction description as applied by the financial institution
     */
    description: string;
    /**
     * Origination Date and Time
     */
    originated?: Date;
    /**
     * The time the transaction was posted.
     */
    posted?: Date;
    /**
     * The time the transaction was applied.
     */
    applied?: Date;
    /**
     * The value of the transaction. Negative values mean money was outgoing from the account
     */
    amount: number;
    /**
     * The currency for the transaction amount. AUD assumed if not present
     */
    currency?: string;
    /**
     * The reference for the transaction provided by the originating institution. Empty string if no data provided
     */
    reference: string;
    card?: DioBankAccountTransactionCard;
    bpay?: DioBankAccountTransactionBPAY;
    apcs?: DioBankAccountTransactionAPCS;
    npp?: DioBankAccountTransactionNPP;
}