/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Deep Thought Exception Type
 */
export type DioExceptionType = 'INVALID_BRAND' | 'INVALID_BRANCH' | 'INVALID_JSON' | 'INVALID_PARAMETER_FORMAT' | 'VALIDATION_ERROR' | 'INVALID_BRAND_AND_PRODUCT' | 'UNSUPPORTED_PRODUCT_SCHEME_TYPE' | 'DATABASE_ERROR' | 'INVALID_PRODUCT' | 'INVALID_BUNDLE' | 'INVALID_CUSTOMER' | 'INVALID_ACCOUNT' | 'INVALID_ASSOCIATION';

export const DioExceptionType = {
    INVALIDBRAND: 'INVALID_BRAND' as DioExceptionType,
    INVALIDBRANCH: 'INVALID_BRANCH' as DioExceptionType,
    INVALIDJSON: 'INVALID_JSON' as DioExceptionType,
    INVALIDPARAMETERFORMAT: 'INVALID_PARAMETER_FORMAT' as DioExceptionType,
    VALIDATIONERROR: 'VALIDATION_ERROR' as DioExceptionType,
    INVALIDBRANDANDPRODUCT: 'INVALID_BRAND_AND_PRODUCT' as DioExceptionType,
    UNSUPPORTEDPRODUCTSCHEMETYPE: 'UNSUPPORTED_PRODUCT_SCHEME_TYPE' as DioExceptionType,
    DATABASEERROR: 'DATABASE_ERROR' as DioExceptionType,
    INVALIDPRODUCT: 'INVALID_PRODUCT' as DioExceptionType,
    INVALIDBUNDLE: 'INVALID_BUNDLE' as DioExceptionType,
    INVALIDCUSTOMER: 'INVALID_CUSTOMER' as DioExceptionType,
    INVALIDACCOUNT: 'INVALID_ACCOUNT' as DioExceptionType,
    INVALIDASSOCIATION: 'INVALID_ASSOCIATION' as DioExceptionType
};