/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DioBankAccount } from './dioBankAccount';
import { DioCustomer } from './dioCustomer';

/**
 * An access list for a Customer Account within a Grant
 */
export interface DioGrantAccount { 
    /**
     * Deep Thought Customer Account Association Identifier
     */
    id: string;
    customer?: DioCustomer;
    bankAccount?: DioBankAccount;
    owner?: boolean;
    /**
     * Granted Permissions
     */
    permissions?: Array<DioGrantAccount.PermissionsEnum>;
}
export namespace DioGrantAccount {
    export type PermissionsEnum = 'ACCOUNTS_BASIC_READ' | 'ACCOUNTS_DETAIL_READ' | 'TRANSACTIONS_READ' | 'PAYEES_READ' | 'PAYMENTS_READ' | 'CUSTOMER_BASIC_READ' | 'CUSTOMER_DETAIL_READ';
    export const PermissionsEnum = {
        ACCOUNTSBASICREAD: 'ACCOUNTS_BASIC_READ' as PermissionsEnum,
        ACCOUNTSDETAILREAD: 'ACCOUNTS_DETAIL_READ' as PermissionsEnum,
        TRANSACTIONSREAD: 'TRANSACTIONS_READ' as PermissionsEnum,
        PAYEESREAD: 'PAYEES_READ' as PermissionsEnum,
        PAYMENTSREAD: 'PAYMENTS_READ' as PermissionsEnum,
        CUSTOMERBASICREAD: 'CUSTOMER_BASIC_READ' as PermissionsEnum,
        CUSTOMERDETAILREAD: 'CUSTOMER_DETAIL_READ' as PermissionsEnum
    };
}