/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CdrCommonPerson } from './cdrCommonPerson';
import { DioAddress } from './dioAddress';
import { DioEmail } from './dioEmail';
import { DioPersonPrefix } from './dioPersonPrefix';
import { DioPersonSuffix } from './dioPersonSuffix';
import { DioPhoneNumber } from './dioPhoneNumber';
import { DioSchemeType } from './dioSchemeType';

/**
 * A Deep Thought Person Container
 */
export interface DioPerson { 
    /**
     * Deep Thought Person Identifier
     */
    id: string;
    schemeType: DioSchemeType;
    prefix?: DioPersonPrefix;
    /**
     * For people with single names this field need not be present.  The single name should be in the lastName field
     */
    firstName?: string;
    /**
     * For people with single names the single name should be in this field
     */
    lastName: string;
    /**
     * Field is mandatory but array may be empty
     */
    middleNames: Array<string>;
    suffix?: DioPersonSuffix;
    phone?: DioPhoneNumber;
    email?: DioEmail;
    address?: DioAddress;
    cdrCommon: CdrCommonPerson;
}