/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * Person Suffixes
 */
export type DioPersonSuffix = 'II' | 'III' | 'IV' | 'AC' | 'CH' | 'ESQ' | 'JNR' | 'MHA' | 'MLC' | 'MP' | 'SNR' | 'BM' | 'BEM' | 'COMDC' | 'CV' | 'DFM' | 'DSC' | 'DSM' | 'GC' | 'KB' | 'KCMG_DCMG' | 'KCB_DCB' | 'KBE_DBE' | 'KCVO_DCVO' | 'AK_AD' | 'KG' | 'KT' | 'OAM' | 'MHR' | 'MLA' | 'AM' | 'MBE' | 'MC' | 'OC' | 'AO' | 'OBE' | 'OM' | 'QC' | 'SC' | 'VC';

export const DioPersonSuffix = {
    II: 'II' as DioPersonSuffix,
    III: 'III' as DioPersonSuffix,
    IV: 'IV' as DioPersonSuffix,
    AC: 'AC' as DioPersonSuffix,
    CH: 'CH' as DioPersonSuffix,
    ESQ: 'ESQ' as DioPersonSuffix,
    JNR: 'JNR' as DioPersonSuffix,
    MHA: 'MHA' as DioPersonSuffix,
    MLC: 'MLC' as DioPersonSuffix,
    MP: 'MP' as DioPersonSuffix,
    SNR: 'SNR' as DioPersonSuffix,
    BM: 'BM' as DioPersonSuffix,
    BEM: 'BEM' as DioPersonSuffix,
    COMDC: 'COMDC' as DioPersonSuffix,
    CV: 'CV' as DioPersonSuffix,
    DFM: 'DFM' as DioPersonSuffix,
    DSC: 'DSC' as DioPersonSuffix,
    DSM: 'DSM' as DioPersonSuffix,
    GC: 'GC' as DioPersonSuffix,
    KB: 'KB' as DioPersonSuffix,
    KCMGDCMG: 'KCMG_DCMG' as DioPersonSuffix,
    KCBDCB: 'KCB_DCB' as DioPersonSuffix,
    KBEDBE: 'KBE_DBE' as DioPersonSuffix,
    KCVODCVO: 'KCVO_DCVO' as DioPersonSuffix,
    AKAD: 'AK_AD' as DioPersonSuffix,
    KG: 'KG' as DioPersonSuffix,
    KT: 'KT' as DioPersonSuffix,
    OAM: 'OAM' as DioPersonSuffix,
    MHR: 'MHR' as DioPersonSuffix,
    MLA: 'MLA' as DioPersonSuffix,
    AM: 'AM' as DioPersonSuffix,
    MBE: 'MBE' as DioPersonSuffix,
    MC: 'MC' as DioPersonSuffix,
    OC: 'OC' as DioPersonSuffix,
    AO: 'AO' as DioPersonSuffix,
    OBE: 'OBE' as DioPersonSuffix,
    OM: 'OM' as DioPersonSuffix,
    QC: 'QC' as DioPersonSuffix,
    SC: 'SC' as DioPersonSuffix,
    VC: 'VC' as DioPersonSuffix
};