/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RequestGrantCustomerAccount } from './requestGrantCustomerAccount';

/**
 * Request for create or update of Grant
 */
export interface RequestGrant { 
    /**
     * Token Subject Identifier
     */
    subject: string;
    /**
     * How long should the grant remain (in seconds), if supplied in update will extend by this length, if not supplied will default to 30 days
     */
    length?: number;
    /**
     * Customer Accounts with Permissions
     */
    customerAccounts: Array<RequestGrantCustomerAccount>;
}