/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DioAccountStatus } from './dioAccountStatus';
import { DioBankAccountCreditCard } from './dioBankAccountCreditCard';
import { DioBankAccountLoanAccount } from './dioBankAccountLoanAccount';
import { DioBankAccountTermDeposit } from './dioBankAccountTermDeposit';
import { DioBankAccountType } from './dioBankAccountType';
import { DioSchemeType } from './dioSchemeType';

/**
 * Request for create or update of a Bank Account
 */
export interface RequestBankAccount { 
    schemeType: DioSchemeType;
    status?: DioAccountStatus;
    productCategory: DioBankAccountType;
    /**
     * The display name of the account as defined by the bank. This should not incorporate account numbers or PANs. If it does the values should be masked according to the rules of the MaskedAccountString common type.
     */
    displayName: string;
    /**
     * A customer supplied nick name for the account
     */
    nickName?: string;
    /**
     * Account ID to assign the new account
     */
    accountNumber?: number;
    /**
     * Associated Product Bundle
     */
    bundleId?: string;
    /**
     * Associated Product ID
     */
    product: string;
    termDeposit?: DioBankAccountTermDeposit;
    creditCard?: DioBankAccountCreditCard;
    loanAccount?: DioBankAccountLoanAccount;
}