/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FormLabelValue } from './formLabelValue';

/**
 * Lists of Common Value types for use in Form select fields
 */
export interface ResponseGetTypes { 
    /**
     * Fields included in this payload
     */
    fieldNames?: Array<string>;
    /**
     * Type of flat or unit for the address
     */
    ADDRESS_PAF_FLAT_UNIT_TYPE?: Array<FormLabelValue>;
    /**
     * Floor or level type for the address
     */
    ADDRESS_PAF_FLOOR_LEVEL_TYPE?: Array<FormLabelValue>;
    /**
     * Postal Delivery Type for the Address
     */
    ADDRESS_PAF_POSTAL_DELIVERY_TYPE?: Array<FormLabelValue>;
    /**
     * Australian State for the Address
     */
    ADDRESS_PAF_STATE_TYPE?: Array<FormLabelValue>;
    /**
     * Street Suffix for the Address
     */
    ADDRESS_PAF_STREET_SUFFIX?: Array<FormLabelValue>;
    /**
     * Street Type for the Address
     */
    ADDRESS_PAF_STREET_TYPE?: Array<FormLabelValue>;
    /**
     * Purpose for the Address
     */
    ADDRESS_PURPOSE?: Array<FormLabelValue>;
    /**
     * Banking Account Status
     */
    BANKING_ACCOUNT_STATUS?: Array<FormLabelValue>;
    /**
     * Banking Account Status with All Status
     */
    BANKING_ACCOUNT_STATUS_WITH_ALL?: Array<FormLabelValue>;
    /**
     * Banking Account Loan Repayment Type
     */
    BANKING_LOAN_REPAYMENT_TYPE?: Array<FormLabelValue>;
    /**
     * Banking Payee Type
     */
    BANKING_PAYEE_TYPE?: Array<FormLabelValue>;
    /**
     * Banking Payee Type with All
     */
    BANKING_PAYEE_TYPE_WITH_ALL?: Array<FormLabelValue>;
    /**
     * Enumerated field giving the treatment where a scheduled payment date is not a business day.
     */
    BANKING_PAYMENT_NON_BUSINESS_DAY_TREATMENT?: Array<FormLabelValue>;
    /**
     * Banking Product Categories
     */
    BANKING_PRODUCT_CATEGORY?: Array<FormLabelValue>;
    /**
     * Banking Product Constraint Type
     */
    BANKING_PRODUCT_CONSTRAINT_TYPE?: Array<FormLabelValue>;
    /**
     * Banking Product Deposit Rate Type
     */
    BANKING_PRODUCT_DEPOSIT_RATE_TYPE?: Array<FormLabelValue>;
    /**
     * Banking Product Discount Eligibility Type
     */
    BANKING_PRODUCT_DISCOUNT_ELIGIBILITY_TYPE?: Array<FormLabelValue>;
    /**
     * Banking Product Discount Type
     */
    BANKING_PRODUCT_DISCOUNT_TYPE?: Array<FormLabelValue>;
    /**
     * Banking Product Effective Filter with All
     */
    BANKING_PRODUCT_EFFECTIVE_WITH_ALL?: Array<FormLabelValue>;
    /**
     * Banking Product Eligibility Criteria Type
     */
    BANKING_PRODUCT_ELIGIBILITY_TYPE?: Array<FormLabelValue>;
    /**
     * Banking Product Feature Type
     */
    BANKING_PRODUCT_FEATURE_TYPE?: Array<FormLabelValue>;
    /**
     * Banking Product Fee Type
     */
    BANKING_PRODUCT_FEE_TYPE?: Array<FormLabelValue>;
    /**
     * Banking Product Lending Rate Interest Payment Configuration
     */
    BANKING_PRODUCT_LENDING_RATE_INTEREST_PAYMENT_TYPE?: Array<FormLabelValue>;
    /**
     * Banking Product: Lending Rate Type
     */
    BANKING_PRODUCT_LENDING_RATE_TYPE?: Array<FormLabelValue>;
    /**
     * Banking Product: Rate Tier Application Method
     */
    BANKING_PRODUCT_RATE_TIER_APPLICATION_METHOD?: Array<FormLabelValue>;
    /**
     * Banking: Scheduled Payment Status
     */
    BANKING_SCHEDULED_PAYMENT_STATUS?: Array<FormLabelValue>;
    /**
     * Banking: Term Deposit Maturity Instructions
     */
    BANKING_TERM_DEPOSIT_MATURITY_INSTRUCTIONS?: Array<FormLabelValue>;
    /**
     * Banking Transaction: NPP Service Overlay
     */
    BANKING_TRANSACTION_SERVICE?: Array<FormLabelValue>;
    /**
     * Banking: Transaction Status
     */
    BANKING_TRANSACTION_STATUS?: Array<FormLabelValue>;
    /**
     * Banking: Transaction Type
     */
    BANKING_TRANSACTION_TYPE?: Array<FormLabelValue>;
    /**
     * Common Discovery: Service Status Type
     */
    COMMON_DISCOVERY_STATUS_TYPE?: Array<FormLabelValue>;
    /**
     * Common: Email Address Purpose
     */
    COMMON_EMAIL_ADDRESS_PURPOSE?: Array<FormLabelValue>;
    /**
     * Common: Organisation Type
     */
    COMMON_ORGANISATION_TYPE?: Array<FormLabelValue>;
    /**
     * Common: Phone Number Purpose
     */
    COMMON_PHONE_NUMBER_PURPOSE?: Array<FormLabelValue>;
    /**
     * Common: Unit of Measure
     */
    COMMON_UNIT_OF_MEASURE_TYPE?: Array<FormLabelValue>;
    /**
     * Day of Week
     */
    COMMON_WEEK_DAY?: Array<FormLabelValue>;
    /**
     * Payload Type: Address
     */
    PAYLOAD_TYPE_ADDRESS?: Array<FormLabelValue>;
    /**
     * Payload Type: Banking Account
     */
    PAYLOAD_TYPE_BANKING_ACCOUNT?: Array<FormLabelValue>;
    /**
     * Payload Type: Domestic Payee
     */
    PAYLOAD_TYPE_BANKING_DOMESTIC_PAYEE?: Array<FormLabelValue>;
    /**
     * Payload Type: Domestic Payee PayID Identifier Type
     */
    PAYLOAD_TYPE_BANKING_DOMESTIC_PAYEE_PAY_ID?: Array<FormLabelValue>;
    /**
     * Payload Type: Banking Payee Type
     */
    PAYLOAD_TYPE_BANKING_PAYEE?: Array<FormLabelValue>;
    /**
     * Payload Type: Banking Scheduled Payment Recurrence
     */
    PAYLOAD_TYPE_BANKING_SCHEDULED_PAYMENT_RECURRENCE?: Array<FormLabelValue>;
    /**
     * Payload Type: Banking Scheduled Payment Target
     */
    PAYLOAD_TYPE_BANKING_SCHEDULED_PAYMENT_TO?: Array<FormLabelValue>;
    /**
     * Payload Type: Customer Type
     */
    PAYLOAD_TYPE_CUSTOMER?: Array<FormLabelValue>;
    /**
     * Payload Type: Transaction Extension Type
     */
    PAYLOAD_TYPE_TRANSACTION_EXTENSION?: Array<FormLabelValue>;
}