apiVersion: v1
kind: Service
metadata:
  labels:
    role: cdr-dr-client
  name: cdr-dr-client
spec:
  ports:
  - name: cdr-dr-client
    port: 8080
    targetPort: 7878
  selector:
    role: cdr-dr-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: cdr-dr-client
  name: cdr-dr-client
spec:
  replicas: 1
  selector:
    matchLabels:
      role: cdr-dr-client
  template:
    metadata:
      labels:
        role: cdr-dr-client
      name: cdr-dr-client
    spec:
      initContainers:
      - name: init
        image: curlimages/curl:latest
        command: ['sh', '-c', 'until curl --connect-timeout 1 --silent -k https://pingaccess:3000 ; do echo waiting for admin ; sleep 3 ; done']
      - name: init-pingdir
        image: curlimages/curl:latest
        command: ['sh', '-c', 'until curl --connect-timeout 1 --silent -k https://pingdirectory:1443 ; do echo waiting for admin ; sleep 3 ; done']
      containers:
      - envFrom:
        - configMapRef:
            name: cdr-dr-client-environment-variables
        image: cdrsandbox/sample-dr-client:20200916
        imagePullPolicy: Always
        name: cdr-dr-client
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "1"
            memory: 0.5Gi
          requests:
            cpu: "0.5"
            memory: 0.25Gi
