export * from './bankAccountAdmin.service';
import { BankAccountAdminService } from './bankAccountAdmin.service';
export * from './bankDirectDebitsAdmin.service';
import { BankDirectDebitsAdminService } from './bankDirectDebitsAdmin.service';
export * from './bankPayeeAdmin.service';
import { BankPayeeAdminService } from './bankPayeeAdmin.service';
export * from './bankScheduledPaymentAdmin.service';
import { BankScheduledPaymentAdminService } from './bankScheduledPaymentAdmin.service';
export * from './bankTransactionAdmin.service';
import { BankTransactionAdminService } from './bankTransactionAdmin.service';
export * from './branchAdmin.service';
import { BranchAdminService } from './branchAdmin.service';
export * from './brandAdmin.service';
import { BrandAdminService } from './brandAdmin.service';
export * from './bundleAdmin.service';
import { BundleAdminService } from './bundleAdmin.service';
export * from './customerAdmin.service';
import { CustomerAdminService } from './customerAdmin.service';
export * from './grantAdmin.service';
import { GrantAdminService } from './grantAdmin.service';
export * from './productAdmin.service';
import { ProductAdminService } from './productAdmin.service';
export * from './type.service';
import { TypeService } from './type.service';
export const APIS = [BankAccountAdminService, BankDirectDebitsAdminService, BankPayeeAdminService, BankScheduledPaymentAdminService, BankTransactionAdminService, BranchAdminService, BrandAdminService, BundleAdminService, CustomerAdminService, GrantAdminService, ProductAdminService, TypeService];
