/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { DioCustomerPayee } from '../model/dioCustomerPayee';
import { ValidationListException } from '../model/validationListException';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class BankPayeeAdminService {

    protected basePath = 'http://localhost:8080/dio-au';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Create a Payee
     * Creates and Returns a new Payee
     * @param brandId 
     * @param customerId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createPayee(brandId: string, customerId: string, body?: DioCustomerPayee, observe?: 'body', reportProgress?: boolean): Observable<DioCustomerPayee>;
    public createPayee(brandId: string, customerId: string, body?: DioCustomerPayee, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioCustomerPayee>>;
    public createPayee(brandId: string, customerId: string, body?: DioCustomerPayee, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioCustomerPayee>>;
    public createPayee(brandId: string, customerId: string, body?: DioCustomerPayee, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling createPayee.');
        }

        if (customerId === null || customerId === undefined) {
            throw new Error('Required parameter customerId was null or undefined when calling createPayee.');
        }


        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DioCustomerPayee>('post',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer/${encodeURIComponent(String(customerId))}/payee`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete a single Payee
     * Deletes a Payee
     * @param brandId 
     * @param customerId 
     * @param payeeId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deletePayee(brandId: string, customerId: string, payeeId: string, observe?: 'body', reportProgress?: boolean): Observable<DioCustomerPayee>;
    public deletePayee(brandId: string, customerId: string, payeeId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioCustomerPayee>>;
    public deletePayee(brandId: string, customerId: string, payeeId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioCustomerPayee>>;
    public deletePayee(brandId: string, customerId: string, payeeId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling deletePayee.');
        }

        if (customerId === null || customerId === undefined) {
            throw new Error('Required parameter customerId was null or undefined when calling deletePayee.');
        }

        if (payeeId === null || payeeId === undefined) {
            throw new Error('Required parameter payeeId was null or undefined when calling deletePayee.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<DioCustomerPayee>('delete',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer/${encodeURIComponent(String(customerId))}/payee/${encodeURIComponent(String(payeeId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a single Payee
     * Returns a single payee entry
     * @param brandId 
     * @param customerId 
     * @param payeeId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPayee(brandId: string, customerId: string, payeeId: string, observe?: 'body', reportProgress?: boolean): Observable<DioCustomerPayee>;
    public getPayee(brandId: string, customerId: string, payeeId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioCustomerPayee>>;
    public getPayee(brandId: string, customerId: string, payeeId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioCustomerPayee>>;
    public getPayee(brandId: string, customerId: string, payeeId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling getPayee.');
        }

        if (customerId === null || customerId === undefined) {
            throw new Error('Required parameter customerId was null or undefined when calling getPayee.');
        }

        if (payeeId === null || payeeId === undefined) {
            throw new Error('Required parameter payeeId was null or undefined when calling getPayee.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<DioCustomerPayee>('get',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer/${encodeURIComponent(String(customerId))}/payee/${encodeURIComponent(String(payeeId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List all Payees
     * List all Payees
     * @param brandId 
     * @param customerId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listPayees(brandId: string, customerId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<DioCustomerPayee>>;
    public listPayees(brandId: string, customerId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DioCustomerPayee>>>;
    public listPayees(brandId: string, customerId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DioCustomerPayee>>>;
    public listPayees(brandId: string, customerId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling listPayees.');
        }

        if (customerId === null || customerId === undefined) {
            throw new Error('Required parameter customerId was null or undefined when calling listPayees.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<DioCustomerPayee>>('get',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer/${encodeURIComponent(String(customerId))}/payee`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update a single Payee
     * Updates and Returns an existing Payee
     * @param brandId 
     * @param customerId 
     * @param payeeId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updatePayee(brandId: string, customerId: string, payeeId: string, body?: DioCustomerPayee, observe?: 'body', reportProgress?: boolean): Observable<DioCustomerPayee>;
    public updatePayee(brandId: string, customerId: string, payeeId: string, body?: DioCustomerPayee, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioCustomerPayee>>;
    public updatePayee(brandId: string, customerId: string, payeeId: string, body?: DioCustomerPayee, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioCustomerPayee>>;
    public updatePayee(brandId: string, customerId: string, payeeId: string, body?: DioCustomerPayee, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling updatePayee.');
        }

        if (customerId === null || customerId === undefined) {
            throw new Error('Required parameter customerId was null or undefined when calling updatePayee.');
        }

        if (payeeId === null || payeeId === undefined) {
            throw new Error('Required parameter payeeId was null or undefined when calling updatePayee.');
        }


        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DioCustomerPayee>('put',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer/${encodeURIComponent(String(customerId))}/payee/${encodeURIComponent(String(payeeId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
