/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { DioBankAccountDirectDebit } from '../model/dioBankAccountDirectDebit';
import { ValidationListException } from '../model/validationListException';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class BankDirectDebitsAdminService {

    protected basePath = 'http://localhost:8080/dio-au';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Create a DirectDebit
     * Creates and Returns a new Bank Account DirectDebit
     * @param brandId 
     * @param branchId 
     * @param accountId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createDirectDebit(brandId: string, branchId: string, accountId: string, body?: DioBankAccountDirectDebit, observe?: 'body', reportProgress?: boolean): Observable<DioBankAccountDirectDebit>;
    public createDirectDebit(brandId: string, branchId: string, accountId: string, body?: DioBankAccountDirectDebit, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioBankAccountDirectDebit>>;
    public createDirectDebit(brandId: string, branchId: string, accountId: string, body?: DioBankAccountDirectDebit, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioBankAccountDirectDebit>>;
    public createDirectDebit(brandId: string, branchId: string, accountId: string, body?: DioBankAccountDirectDebit, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling createDirectDebit.');
        }

        if (branchId === null || branchId === undefined) {
            throw new Error('Required parameter branchId was null or undefined when calling createDirectDebit.');
        }

        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling createDirectDebit.');
        }


        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DioBankAccountDirectDebit>('post',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/branch/${encodeURIComponent(String(branchId))}/bank-account/${encodeURIComponent(String(accountId))}/direct-debit`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete a single DirectDebit
     * Deletes a single Bank Account DirectDebit
     * @param brandId 
     * @param branchId 
     * @param accountId 
     * @param directDebitId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteDirectDebit(brandId: string, branchId: string, accountId: string, directDebitId: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteDirectDebit(brandId: string, branchId: string, accountId: string, directDebitId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteDirectDebit(brandId: string, branchId: string, accountId: string, directDebitId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteDirectDebit(brandId: string, branchId: string, accountId: string, directDebitId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling deleteDirectDebit.');
        }

        if (branchId === null || branchId === undefined) {
            throw new Error('Required parameter branchId was null or undefined when calling deleteDirectDebit.');
        }

        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling deleteDirectDebit.');
        }

        if (directDebitId === null || directDebitId === undefined) {
            throw new Error('Required parameter directDebitId was null or undefined when calling deleteDirectDebit.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/branch/${encodeURIComponent(String(branchId))}/bank-account/${encodeURIComponent(String(accountId))}/direct-debit/${encodeURIComponent(String(directDebitId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a single Bank DirectDebit
     * Returns a single direct-debit detail
     * @param brandId 
     * @param branchId 
     * @param accountId 
     * @param directDebitId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getDirectDebit(brandId: string, branchId: string, accountId: string, directDebitId: string, observe?: 'body', reportProgress?: boolean): Observable<DioBankAccountDirectDebit>;
    public getDirectDebit(brandId: string, branchId: string, accountId: string, directDebitId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioBankAccountDirectDebit>>;
    public getDirectDebit(brandId: string, branchId: string, accountId: string, directDebitId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioBankAccountDirectDebit>>;
    public getDirectDebit(brandId: string, branchId: string, accountId: string, directDebitId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling getDirectDebit.');
        }

        if (branchId === null || branchId === undefined) {
            throw new Error('Required parameter branchId was null or undefined when calling getDirectDebit.');
        }

        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling getDirectDebit.');
        }

        if (directDebitId === null || directDebitId === undefined) {
            throw new Error('Required parameter directDebitId was null or undefined when calling getDirectDebit.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<DioBankAccountDirectDebit>('get',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/branch/${encodeURIComponent(String(branchId))}/bank-account/${encodeURIComponent(String(accountId))}/direct-debit/${encodeURIComponent(String(directDebitId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List Direct Debits
     * List Direct Debits belonging to a Single Account
     * @param brandId 
     * @param branchId 
     * @param accountId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listDirectDebits(brandId: string, branchId: string, accountId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<DioBankAccountDirectDebit>>;
    public listDirectDebits(brandId: string, branchId: string, accountId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DioBankAccountDirectDebit>>>;
    public listDirectDebits(brandId: string, branchId: string, accountId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DioBankAccountDirectDebit>>>;
    public listDirectDebits(brandId: string, branchId: string, accountId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling listDirectDebits.');
        }

        if (branchId === null || branchId === undefined) {
            throw new Error('Required parameter branchId was null or undefined when calling listDirectDebits.');
        }

        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling listDirectDebits.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<DioBankAccountDirectDebit>>('get',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/branch/${encodeURIComponent(String(branchId))}/bank-account/${encodeURIComponent(String(accountId))}/direct-debit`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update a single DirectDebit
     * Updates and Returns an existing Bank Account DirectDebit
     * @param brandId 
     * @param branchId 
     * @param accountId 
     * @param directDebitId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateDirectDebit(brandId: string, branchId: string, accountId: string, directDebitId: string, body?: DioBankAccountDirectDebit, observe?: 'body', reportProgress?: boolean): Observable<DioBankAccountDirectDebit>;
    public updateDirectDebit(brandId: string, branchId: string, accountId: string, directDebitId: string, body?: DioBankAccountDirectDebit, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioBankAccountDirectDebit>>;
    public updateDirectDebit(brandId: string, branchId: string, accountId: string, directDebitId: string, body?: DioBankAccountDirectDebit, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioBankAccountDirectDebit>>;
    public updateDirectDebit(brandId: string, branchId: string, accountId: string, directDebitId: string, body?: DioBankAccountDirectDebit, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling updateDirectDebit.');
        }

        if (branchId === null || branchId === undefined) {
            throw new Error('Required parameter branchId was null or undefined when calling updateDirectDebit.');
        }

        if (accountId === null || accountId === undefined) {
            throw new Error('Required parameter accountId was null or undefined when calling updateDirectDebit.');
        }

        if (directDebitId === null || directDebitId === undefined) {
            throw new Error('Required parameter directDebitId was null or undefined when calling updateDirectDebit.');
        }


        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DioBankAccountDirectDebit>('put',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/branch/${encodeURIComponent(String(branchId))}/bank-account/${encodeURIComponent(String(accountId))}/direct-debit/${encodeURIComponent(String(directDebitId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
