/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { DioCustomerScheduledPayment } from '../model/dioCustomerScheduledPayment';
import { ValidationListException } from '../model/validationListException';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class BankScheduledPaymentAdminService {

    protected basePath = 'http://localhost:8080/dio-au';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Create a Scheduled Payment
     * Creates and Returns a new Scheduled Payment
     * @param brandId 
     * @param customerId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createScheduledPayment(brandId: string, customerId: string, body?: DioCustomerScheduledPayment, observe?: 'body', reportProgress?: boolean): Observable<DioCustomerScheduledPayment>;
    public createScheduledPayment(brandId: string, customerId: string, body?: DioCustomerScheduledPayment, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioCustomerScheduledPayment>>;
    public createScheduledPayment(brandId: string, customerId: string, body?: DioCustomerScheduledPayment, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioCustomerScheduledPayment>>;
    public createScheduledPayment(brandId: string, customerId: string, body?: DioCustomerScheduledPayment, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling createScheduledPayment.');
        }

        if (customerId === null || customerId === undefined) {
            throw new Error('Required parameter customerId was null or undefined when calling createScheduledPayment.');
        }


        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DioCustomerScheduledPayment>('post',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer/${encodeURIComponent(String(customerId))}/scheduled-payment`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete a single Scheduled Payment
     * Deletes a Scheduled Payment
     * @param brandId 
     * @param customerId 
     * @param scheduledPaymentId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteScheduledPayment(brandId: string, customerId: string, scheduledPaymentId: string, observe?: 'body', reportProgress?: boolean): Observable<DioCustomerScheduledPayment>;
    public deleteScheduledPayment(brandId: string, customerId: string, scheduledPaymentId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioCustomerScheduledPayment>>;
    public deleteScheduledPayment(brandId: string, customerId: string, scheduledPaymentId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioCustomerScheduledPayment>>;
    public deleteScheduledPayment(brandId: string, customerId: string, scheduledPaymentId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling deleteScheduledPayment.');
        }

        if (customerId === null || customerId === undefined) {
            throw new Error('Required parameter customerId was null or undefined when calling deleteScheduledPayment.');
        }

        if (scheduledPaymentId === null || scheduledPaymentId === undefined) {
            throw new Error('Required parameter scheduledPaymentId was null or undefined when calling deleteScheduledPayment.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<DioCustomerScheduledPayment>('delete',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer/${encodeURIComponent(String(customerId))}/scheduled-payment/${encodeURIComponent(String(scheduledPaymentId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a single Scheduled Payment
     * Returns a single scheduledPayment entry
     * @param brandId 
     * @param customerId 
     * @param scheduledPaymentId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getScheduledPayment(brandId: string, customerId: string, scheduledPaymentId: string, observe?: 'body', reportProgress?: boolean): Observable<DioCustomerScheduledPayment>;
    public getScheduledPayment(brandId: string, customerId: string, scheduledPaymentId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioCustomerScheduledPayment>>;
    public getScheduledPayment(brandId: string, customerId: string, scheduledPaymentId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioCustomerScheduledPayment>>;
    public getScheduledPayment(brandId: string, customerId: string, scheduledPaymentId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling getScheduledPayment.');
        }

        if (customerId === null || customerId === undefined) {
            throw new Error('Required parameter customerId was null or undefined when calling getScheduledPayment.');
        }

        if (scheduledPaymentId === null || scheduledPaymentId === undefined) {
            throw new Error('Required parameter scheduledPaymentId was null or undefined when calling getScheduledPayment.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<DioCustomerScheduledPayment>('get',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer/${encodeURIComponent(String(customerId))}/scheduled-payment/${encodeURIComponent(String(scheduledPaymentId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List all Scheduled Payments
     * List all Scheduled Payments
     * @param brandId 
     * @param customerId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listScheduledPayments(brandId: string, customerId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<DioCustomerScheduledPayment>>;
    public listScheduledPayments(brandId: string, customerId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DioCustomerScheduledPayment>>>;
    public listScheduledPayments(brandId: string, customerId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DioCustomerScheduledPayment>>>;
    public listScheduledPayments(brandId: string, customerId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling listScheduledPayments.');
        }

        if (customerId === null || customerId === undefined) {
            throw new Error('Required parameter customerId was null or undefined when calling listScheduledPayments.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<DioCustomerScheduledPayment>>('get',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer/${encodeURIComponent(String(customerId))}/scheduled-payment`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update a single Scheduled Payment
     * Updates and Returns an existing Scheduled Payment
     * @param brandId 
     * @param customerId 
     * @param scheduledPaymentId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateScheduledPayment(brandId: string, customerId: string, scheduledPaymentId: string, body?: DioCustomerScheduledPayment, observe?: 'body', reportProgress?: boolean): Observable<DioCustomerScheduledPayment>;
    public updateScheduledPayment(brandId: string, customerId: string, scheduledPaymentId: string, body?: DioCustomerScheduledPayment, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioCustomerScheduledPayment>>;
    public updateScheduledPayment(brandId: string, customerId: string, scheduledPaymentId: string, body?: DioCustomerScheduledPayment, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioCustomerScheduledPayment>>;
    public updateScheduledPayment(brandId: string, customerId: string, scheduledPaymentId: string, body?: DioCustomerScheduledPayment, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling updateScheduledPayment.');
        }

        if (customerId === null || customerId === undefined) {
            throw new Error('Required parameter customerId was null or undefined when calling updateScheduledPayment.');
        }

        if (scheduledPaymentId === null || scheduledPaymentId === undefined) {
            throw new Error('Required parameter scheduledPaymentId was null or undefined when calling updateScheduledPayment.');
        }


        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DioCustomerScheduledPayment>('put',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer/${encodeURIComponent(String(customerId))}/scheduled-payment/${encodeURIComponent(String(scheduledPaymentId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
