/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { DioBankAccount } from '../model/dioBankAccount';
import { RequestBankAccount } from '../model/requestBankAccount';
import { ValidationListException } from '../model/validationListException';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class BankAccountAdminService {

    protected basePath = 'http://localhost:8080/dio-au';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Create a Bank Account
     * Creates and Returns a new Bank Account
     * @param brandId 
     * @param branchId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createBankAccount(brandId: string, branchId: string, body?: RequestBankAccount, observe?: 'body', reportProgress?: boolean): Observable<DioBankAccount>;
    public createBankAccount(brandId: string, branchId: string, body?: RequestBankAccount, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioBankAccount>>;
    public createBankAccount(brandId: string, branchId: string, body?: RequestBankAccount, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioBankAccount>>;
    public createBankAccount(brandId: string, branchId: string, body?: RequestBankAccount, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling createBankAccount.');
        }

        if (branchId === null || branchId === undefined) {
            throw new Error('Required parameter branchId was null or undefined when calling createBankAccount.');
        }


        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DioBankAccount>('post',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/branch/${encodeURIComponent(String(branchId))}/bank-account`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete a single Bank Account
     * Deletes a Bank Account
     * @param brandId 
     * @param branchId 
     * @param bankAccountId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteBankAccount(brandId: string, branchId: string, bankAccountId: string, observe?: 'body', reportProgress?: boolean): Observable<DioBankAccount>;
    public deleteBankAccount(brandId: string, branchId: string, bankAccountId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioBankAccount>>;
    public deleteBankAccount(brandId: string, branchId: string, bankAccountId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioBankAccount>>;
    public deleteBankAccount(brandId: string, branchId: string, bankAccountId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling deleteBankAccount.');
        }

        if (branchId === null || branchId === undefined) {
            throw new Error('Required parameter branchId was null or undefined when calling deleteBankAccount.');
        }

        if (bankAccountId === null || bankAccountId === undefined) {
            throw new Error('Required parameter bankAccountId was null or undefined when calling deleteBankAccount.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<DioBankAccount>('delete',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/branch/${encodeURIComponent(String(branchId))}/bank-account/${encodeURIComponent(String(bankAccountId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a single Bank Account
     * Returns a single bank account entry
     * @param brandId 
     * @param branchId 
     * @param bankAccountId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getBankAccount(brandId: string, branchId: string, bankAccountId: string, observe?: 'body', reportProgress?: boolean): Observable<DioBankAccount>;
    public getBankAccount(brandId: string, branchId: string, bankAccountId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioBankAccount>>;
    public getBankAccount(brandId: string, branchId: string, bankAccountId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioBankAccount>>;
    public getBankAccount(brandId: string, branchId: string, bankAccountId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling getBankAccount.');
        }

        if (branchId === null || branchId === undefined) {
            throw new Error('Required parameter branchId was null or undefined when calling getBankAccount.');
        }

        if (bankAccountId === null || bankAccountId === undefined) {
            throw new Error('Required parameter bankAccountId was null or undefined when calling getBankAccount.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<DioBankAccount>('get',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/branch/${encodeURIComponent(String(branchId))}/bank-account/${encodeURIComponent(String(bankAccountId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List all Bank Accounts
     * List all Bank Accounts
     * @param brandId 
     * @param branchId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listBankAccounts(brandId: string, branchId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<DioBankAccount>>;
    public listBankAccounts(brandId: string, branchId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DioBankAccount>>>;
    public listBankAccounts(brandId: string, branchId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DioBankAccount>>>;
    public listBankAccounts(brandId: string, branchId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling listBankAccounts.');
        }

        if (branchId === null || branchId === undefined) {
            throw new Error('Required parameter branchId was null or undefined when calling listBankAccounts.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<DioBankAccount>>('get',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/branch/${encodeURIComponent(String(branchId))}/bank-account`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update a single Bank Account
     * Updates and Returns an existing BankAccount
     * @param brandId 
     * @param branchId 
     * @param bankAccountId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateBankAccount(brandId: string, branchId: string, bankAccountId: string, body?: RequestBankAccount, observe?: 'body', reportProgress?: boolean): Observable<DioBankAccount>;
    public updateBankAccount(brandId: string, branchId: string, bankAccountId: string, body?: RequestBankAccount, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioBankAccount>>;
    public updateBankAccount(brandId: string, branchId: string, bankAccountId: string, body?: RequestBankAccount, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioBankAccount>>;
    public updateBankAccount(brandId: string, branchId: string, bankAccountId: string, body?: RequestBankAccount, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling updateBankAccount.');
        }

        if (branchId === null || branchId === undefined) {
            throw new Error('Required parameter branchId was null or undefined when calling updateBankAccount.');
        }

        if (bankAccountId === null || bankAccountId === undefined) {
            throw new Error('Required parameter bankAccountId was null or undefined when calling updateBankAccount.');
        }


        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DioBankAccount>('put',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/branch/${encodeURIComponent(String(branchId))}/bank-account/${encodeURIComponent(String(bankAccountId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
