/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { DioBankBranch } from '../model/dioBankBranch';
import { DioCustomer } from '../model/dioCustomer';
import { DioCustomerAccount } from '../model/dioCustomerAccount';
import { RequestCustomerBankAccountConnection } from '../model/requestCustomerBankAccountConnection';
import { ValidationListException } from '../model/validationListException';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CustomerAdminService {

    protected basePath = 'http://localhost:8080/dio-au';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Associate a Customer Account
     * Associates a account with an individual Customer
     * @param brandId 
     * @param customerId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public associateCustomerAccount(brandId: string, customerId: string, body?: RequestCustomerBankAccountConnection, observe?: 'body', reportProgress?: boolean): Observable<DioBankBranch>;
    public associateCustomerAccount(brandId: string, customerId: string, body?: RequestCustomerBankAccountConnection, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioBankBranch>>;
    public associateCustomerAccount(brandId: string, customerId: string, body?: RequestCustomerBankAccountConnection, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioBankBranch>>;
    public associateCustomerAccount(brandId: string, customerId: string, body?: RequestCustomerBankAccountConnection, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling associateCustomerAccount.');
        }

        if (customerId === null || customerId === undefined) {
            throw new Error('Required parameter customerId was null or undefined when calling associateCustomerAccount.');
        }


        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DioBankBranch>('post',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer/${encodeURIComponent(String(customerId))}/account`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Create a Customer
     * Creates and Returns a new Customer
     * @param brandId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createCustomer(brandId: string, body?: DioCustomer, observe?: 'body', reportProgress?: boolean): Observable<DioCustomer>;
    public createCustomer(brandId: string, body?: DioCustomer, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioCustomer>>;
    public createCustomer(brandId: string, body?: DioCustomer, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioCustomer>>;
    public createCustomer(brandId: string, body?: DioCustomer, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling createCustomer.');
        }


        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DioCustomer>('post',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete a single Customer
     * Deletes a Customer
     * @param brandId 
     * @param customerId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteCustomer(brandId: string, customerId: string, observe?: 'body', reportProgress?: boolean): Observable<DioCustomer>;
    public deleteCustomer(brandId: string, customerId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioCustomer>>;
    public deleteCustomer(brandId: string, customerId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioCustomer>>;
    public deleteCustomer(brandId: string, customerId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling deleteCustomer.');
        }

        if (customerId === null || customerId === undefined) {
            throw new Error('Required parameter customerId was null or undefined when calling deleteCustomer.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<DioCustomer>('delete',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer/${encodeURIComponent(String(customerId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a single Customer
     * Returns a single customer entry
     * @param brandId 
     * @param customerId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCustomer(brandId: string, customerId: string, observe?: 'body', reportProgress?: boolean): Observable<DioCustomer>;
    public getCustomer(brandId: string, customerId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioCustomer>>;
    public getCustomer(brandId: string, customerId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioCustomer>>;
    public getCustomer(brandId: string, customerId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling getCustomer.');
        }

        if (customerId === null || customerId === undefined) {
            throw new Error('Required parameter customerId was null or undefined when calling getCustomer.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<DioCustomer>('get',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer/${encodeURIComponent(String(customerId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a single Customer Account Association
     * Returns a single customer account entry
     * @param brandId 
     * @param customerId 
     * @param associationId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCustomerAccountAssociation(brandId: string, customerId: string, associationId: string, observe?: 'body', reportProgress?: boolean): Observable<DioCustomer>;
    public getCustomerAccountAssociation(brandId: string, customerId: string, associationId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioCustomer>>;
    public getCustomerAccountAssociation(brandId: string, customerId: string, associationId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioCustomer>>;
    public getCustomerAccountAssociation(brandId: string, customerId: string, associationId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling getCustomerAccountAssociation.');
        }

        if (customerId === null || customerId === undefined) {
            throw new Error('Required parameter customerId was null or undefined when calling getCustomerAccountAssociation.');
        }

        if (associationId === null || associationId === undefined) {
            throw new Error('Required parameter associationId was null or undefined when calling getCustomerAccountAssociation.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<DioCustomer>('get',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer/${encodeURIComponent(String(customerId))}/account/${encodeURIComponent(String(associationId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List all Customer Accounts
     * List all Customer Accounts
     * @param brandId 
     * @param customerId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listCustomerAccountAssociations(brandId: string, customerId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<DioCustomerAccount>>;
    public listCustomerAccountAssociations(brandId: string, customerId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DioCustomerAccount>>>;
    public listCustomerAccountAssociations(brandId: string, customerId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DioCustomerAccount>>>;
    public listCustomerAccountAssociations(brandId: string, customerId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling listCustomerAccountAssociations.');
        }

        if (customerId === null || customerId === undefined) {
            throw new Error('Required parameter customerId was null or undefined when calling listCustomerAccountAssociations.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<DioCustomerAccount>>('get',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer/${encodeURIComponent(String(customerId))}/account`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List all Customers
     * List all Customers
     * @param brandId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listCustomers(brandId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<DioCustomer>>;
    public listCustomers(brandId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DioCustomer>>>;
    public listCustomers(brandId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DioCustomer>>>;
    public listCustomers(brandId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling listCustomers.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<DioCustomer>>('get',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Unassociate a Customer Bank Account
     * Removes a Customer Account Association
     * @param brandId 
     * @param customerId 
     * @param associationId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public unassociateCustomerAccount(brandId: string, customerId: string, associationId: string, observe?: 'body', reportProgress?: boolean): Observable<DioCustomer>;
    public unassociateCustomerAccount(brandId: string, customerId: string, associationId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioCustomer>>;
    public unassociateCustomerAccount(brandId: string, customerId: string, associationId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioCustomer>>;
    public unassociateCustomerAccount(brandId: string, customerId: string, associationId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling unassociateCustomerAccount.');
        }

        if (customerId === null || customerId === undefined) {
            throw new Error('Required parameter customerId was null or undefined when calling unassociateCustomerAccount.');
        }

        if (associationId === null || associationId === undefined) {
            throw new Error('Required parameter associationId was null or undefined when calling unassociateCustomerAccount.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<DioCustomer>('delete',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer/${encodeURIComponent(String(customerId))}/account/${encodeURIComponent(String(associationId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update a single Customer
     * Updates and Returns an existing Customer
     * @param brandId 
     * @param customerId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateCustomer(brandId: string, customerId: string, body?: DioCustomer, observe?: 'body', reportProgress?: boolean): Observable<DioCustomer>;
    public updateCustomer(brandId: string, customerId: string, body?: DioCustomer, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioCustomer>>;
    public updateCustomer(brandId: string, customerId: string, body?: DioCustomer, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioCustomer>>;
    public updateCustomer(brandId: string, customerId: string, body?: DioCustomer, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (brandId === null || brandId === undefined) {
            throw new Error('Required parameter brandId was null or undefined when calling updateCustomer.');
        }

        if (customerId === null || customerId === undefined) {
            throw new Error('Required parameter customerId was null or undefined when calling updateCustomer.');
        }


        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DioCustomer>('put',`${this.basePath}/v1/brand/${encodeURIComponent(String(brandId))}/customer/${encodeURIComponent(String(customerId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
