/**
 * Deep Thought Administration API
 * This is the Deep Thought Administration API. You can find out more about Deep Thought at [https://github.com/bizaio/deepthought](https://github.com/bizaio/deepthought) or on the [DataRight.io Slack, #oss](https://join.slack.com/t/datarightio/shared_invite/enQtNzAyNTI2MjA2MzU1LTU1NGE4MmQ2N2JiZWI2ODA5MTQ2N2Q0NTRmYmM0OWRlM2U5YzA3NzU5NDYyODlhNjRmNzU3ZDZmNTI0MDE3NjY).
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { DioGrant } from '../model/dioGrant';
import { RequestGrant } from '../model/requestGrant';
import { ValidationListException } from '../model/validationListException';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class GrantAdminService {

    protected basePath = 'http://localhost:8080/dio-au';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Create a Grant
     * Creates and Returns a new Grant
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public createGrant(body?: RequestGrant, observe?: 'body', reportProgress?: boolean): Observable<DioGrant>;
    public createGrant(body?: RequestGrant, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioGrant>>;
    public createGrant(body?: RequestGrant, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioGrant>>;
    public createGrant(body?: RequestGrant, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {


        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DioGrant>('post',`${this.basePath}/v1/grant`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Delete a single Grant
     * Deletes a Grant
     * @param grantId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteGrant(grantId: string, observe?: 'body', reportProgress?: boolean): Observable<DioGrant>;
    public deleteGrant(grantId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioGrant>>;
    public deleteGrant(grantId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioGrant>>;
    public deleteGrant(grantId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (grantId === null || grantId === undefined) {
            throw new Error('Required parameter grantId was null or undefined when calling deleteGrant.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<DioGrant>('delete',`${this.basePath}/v1/grant/${encodeURIComponent(String(grantId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Get a single grant
     * Returns a single grant entry
     * @param grantId 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getGrant(grantId: string, observe?: 'body', reportProgress?: boolean): Observable<DioGrant>;
    public getGrant(grantId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioGrant>>;
    public getGrant(grantId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioGrant>>;
    public getGrant(grantId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (grantId === null || grantId === undefined) {
            throw new Error('Required parameter grantId was null or undefined when calling getGrant.');
        }

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<DioGrant>('get',`${this.basePath}/v1/grant/${encodeURIComponent(String(grantId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * List all Grants
     * List all Grants
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public listGrants(observe?: 'body', reportProgress?: boolean): Observable<Array<DioGrant>>;
    public listGrants(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<DioGrant>>>;
    public listGrants(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<DioGrant>>>;
    public listGrants(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<DioGrant>>('get',`${this.basePath}/v1/grant`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Update a single Grant
     * Updates and Returns an existing Grant
     * @param grantId 
     * @param body 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateGrant(grantId: string, body?: RequestGrant, observe?: 'body', reportProgress?: boolean): Observable<DioGrant>;
    public updateGrant(grantId: string, body?: RequestGrant, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<DioGrant>>;
    public updateGrant(grantId: string, body?: RequestGrant, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<DioGrant>>;
    public updateGrant(grantId: string, body?: RequestGrant, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (grantId === null || grantId === undefined) {
            throw new Error('Required parameter grantId was null or undefined when calling updateGrant.');
        }


        let headers = this.defaultHeaders;

        // authentication (deepthought_auth) required
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<DioGrant>('put',`${this.basePath}/v1/grant/${encodeURIComponent(String(grantId))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
